-- GENERATED by genai-codegen from spec/generativelanguage-v1beta.json (revision 20260831). Do not edit.
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-orphans -Wno-unused-imports #-}

-- | 'Arbitrary' instances and the JSON round-trip property for every
-- generated type. Enum generators produce only the known constructors,
-- never the @Unknown@ fallback, which would decode back to the real
-- constructor and fail the property for the wrong reason.
module Instances (roundTripSpecs) where

import Data.Aeson (FromJSON, ToJSON, Value (..), decode, encode)
import qualified Data.ByteString as BS
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time (Day (..), UTCTime (..))
import Test.Hspec
import Test.Hspec.QuickCheck (prop)
import Test.QuickCheck

import GenAI.Client.Model
import GenAI.Client.Types (Base64Bytes (..))

instance Arbitrary Text where
  arbitrary = T.pack <$> listOf (elements ['a' .. 'z'])

-- | Whole seconds only: sub-second precision does not survive aeson's
-- RFC3339 round-trip reliably.
instance Arbitrary UTCTime where
  arbitrary = do
    d <- choose (0, 40000 :: Integer)
    s <- choose (0, 86399 :: Integer)
    pure (UTCTime (ModifiedJulianDay (40587 + d)) (fromInteger s))

-- | A small, flat JSON value, used for every generated 'Value' field in
-- place of aeson's own instance. Never @Null@: a @Just Null@ in an
-- optional field encodes as a JSON null, and proto3 JSON reads null as
-- absent, so it decodes back as 'Nothing'. Numbers are integral, so the
-- 'Data.Scientific.Scientific' hop is exact.
flatValue :: Gen Value
flatValue =
  oneof
    [ String <$> arbitrary
    , Bool <$> arbitrary
    , Number . fromInteger <$> arbitrary
    ]

-- | Any byte string base64-encodes to something the strict decoder accepts.
instance Arbitrary Base64Bytes where
  arbitrary = Base64Bytes . BS.pack <$> arbitrary

roundTrip :: forall a. (Eq a, ToJSON a, FromJSON a) => a -> Bool
roundTrip x = decode (encode x) == Just x

instance Arbitrary AttributionSourceId where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkAttributionSourceId
      else scale (`div` 2) (AttributionSourceId <$> arbitrary <*> arbitrary)

instance Arbitrary AudioResponseFormatDelivery where
  arbitrary = elements [AudioResponseFormatDeliveryDeliveryUnspecified, AudioResponseFormatDeliveryInline, AudioResponseFormatDeliveryUri]

instance Arbitrary AudioResponseFormatMimeType where
  arbitrary = elements [AudioResponseFormatMimeTypeMimeTypeUnspecified, AudioResponseFormatMimeTypeAudioMp3, AudioResponseFormatMimeTypeAudioOggOpus, AudioResponseFormatMimeTypeAudioL16, AudioResponseFormatMimeTypeAudioWav, AudioResponseFormatMimeTypeAudioAlaw, AudioResponseFormatMimeTypeAudioMulaw]

instance Arbitrary AudioResponseFormat where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkAudioResponseFormat
      else scale (`div` 2) (AudioResponseFormat <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary AudioTranscription where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkAudioTranscription <$> arbitrary
      else scale (`div` 2) (AudioTranscription <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary AudioTranscriptionConfigMode where
  arbitrary = elements [AudioTranscriptionConfigModeModeUnspecified, AudioTranscriptionConfigModeVerbatim, AudioTranscriptionConfigModeSmart]

instance Arbitrary AudioTranscriptionConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkAudioTranscriptionConfig
      else scale (`div` 2) (AudioTranscriptionConfig <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary BatchEmbedContentsRequest where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkBatchEmbedContentsRequest <$> arbitrary
      else scale (`div` 2) (BatchEmbedContentsRequest <$> arbitrary)

instance Arbitrary BatchEmbedContentsResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkBatchEmbedContentsResponse
      else scale (`div` 2) (BatchEmbedContentsResponse <$> arbitrary <*> arbitrary)

instance Arbitrary Blob where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkBlob
      else scale (`div` 2) (Blob <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary CachedContent where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkCachedContent <$> arbitrary
      else scale (`div` 2) (CachedContent <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary CachedContentUsageMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCachedContentUsageMetadata
      else scale (`div` 2) (CachedContentUsageMetadata <$> arbitrary)

instance Arbitrary CandidateFinishReason where
  arbitrary = elements [CandidateFinishReasonFinishReasonUnspecified, CandidateFinishReasonStop, CandidateFinishReasonMaxTokens, CandidateFinishReasonSafety, CandidateFinishReasonRecitation, CandidateFinishReasonLanguage, CandidateFinishReasonOther, CandidateFinishReasonBlocklist, CandidateFinishReasonProhibitedContent, CandidateFinishReasonSpii, CandidateFinishReasonMalformedFunctionCall, CandidateFinishReasonImageSafety, CandidateFinishReasonImageProhibitedContent, CandidateFinishReasonImageOther, CandidateFinishReasonNoImage, CandidateFinishReasonImageRecitation, CandidateFinishReasonUnexpectedToolCall, CandidateFinishReasonTooManyToolCalls, CandidateFinishReasonMissingThoughtSignature, CandidateFinishReasonMalformedResponse, CandidateFinishReasonEscalation]

instance Arbitrary Candidate where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCandidate
      else scale (`div` 2) (Candidate <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary CitationMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCitationMetadata
      else scale (`div` 2) (CitationMetadata <$> arbitrary)

instance Arbitrary CitationSource where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCitationSource
      else scale (`div` 2) (CitationSource <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary CodeExecution where
  arbitrary = pure CodeExecution

instance Arbitrary CodeExecutionResultOutcome where
  arbitrary = elements [CodeExecutionResultOutcomeOutcomeUnspecified, CodeExecutionResultOutcomeOutcomeOk, CodeExecutionResultOutcomeOutcomeFailed, CodeExecutionResultOutcomeOutcomeDeadlineExceeded]

instance Arbitrary CodeExecutionResult where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkCodeExecutionResult <$> arbitrary
      else scale (`div` 2) (CodeExecutionResult <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ComputerUseDisabledSafetyPolicies where
  arbitrary = elements [ComputerUseDisabledSafetyPoliciesSafetyPolicyUnspecified, ComputerUseDisabledSafetyPoliciesFinancialTransactions, ComputerUseDisabledSafetyPoliciesSensitiveDataModification, ComputerUseDisabledSafetyPoliciesCommunicationTool, ComputerUseDisabledSafetyPoliciesAccountCreation, ComputerUseDisabledSafetyPoliciesDataModification, ComputerUseDisabledSafetyPoliciesUserConsentManagement, ComputerUseDisabledSafetyPoliciesLegalTermsAndAgreements]

instance Arbitrary ComputerUseEnvironment where
  arbitrary = elements [ComputerUseEnvironmentEnvironmentUnspecified, ComputerUseEnvironmentEnvironmentBrowser, ComputerUseEnvironmentEnvironmentMobile, ComputerUseEnvironmentEnvironmentDesktop]

instance Arbitrary ComputerUse where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkComputerUse <$> arbitrary
      else scale (`div` 2) (ComputerUse <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary Content where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkContent
      else scale (`div` 2) (Content <$> arbitrary <*> arbitrary)

instance Arbitrary ContentEmbedding where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkContentEmbedding
      else scale (`div` 2) (ContentEmbedding <$> arbitrary <*> arbitrary)

instance Arbitrary CountTokensRequest where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCountTokensRequest
      else scale (`div` 2) (CountTokensRequest <$> arbitrary <*> arbitrary)

instance Arbitrary CountTokensResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCountTokensResponse
      else scale (`div` 2) (CountTokensResponse <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary CreateFileRequest where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCreateFileRequest
      else scale (`div` 2) (CreateFileRequest <$> arbitrary)

instance Arbitrary CreateFileResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkCreateFileResponse
      else scale (`div` 2) (CreateFileResponse <$> arbitrary)

instance Arbitrary DynamicRetrievalConfigMode where
  arbitrary = elements [DynamicRetrievalConfigModeModeUnspecified, DynamicRetrievalConfigModeModeDynamic]

instance Arbitrary DynamicRetrievalConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkDynamicRetrievalConfig
      else scale (`div` 2) (DynamicRetrievalConfig <$> arbitrary <*> arbitrary)

instance Arbitrary EmbedContentConfigTaskType where
  arbitrary = elements [EmbedContentConfigTaskTypeTaskTypeUnspecified, EmbedContentConfigTaskTypeRetrievalQuery, EmbedContentConfigTaskTypeRetrievalDocument, EmbedContentConfigTaskTypeSemanticSimilarity, EmbedContentConfigTaskTypeClassification, EmbedContentConfigTaskTypeClustering, EmbedContentConfigTaskTypeQuestionAnswering, EmbedContentConfigTaskTypeFactVerification, EmbedContentConfigTaskTypeCodeRetrievalQuery]

instance Arbitrary EmbedContentConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkEmbedContentConfig
      else scale (`div` 2) (EmbedContentConfig <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary EmbedContentRequestTaskType where
  arbitrary = elements [EmbedContentRequestTaskTypeTaskTypeUnspecified, EmbedContentRequestTaskTypeRetrievalQuery, EmbedContentRequestTaskTypeRetrievalDocument, EmbedContentRequestTaskTypeSemanticSimilarity, EmbedContentRequestTaskTypeClassification, EmbedContentRequestTaskTypeClustering, EmbedContentRequestTaskTypeQuestionAnswering, EmbedContentRequestTaskTypeFactVerification, EmbedContentRequestTaskTypeCodeRetrievalQuery]

instance Arbitrary EmbedContentRequest where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkEmbedContentRequest <$> arbitrary <*> arbitrary
      else scale (`div` 2) (EmbedContentRequest <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary EmbedContentResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkEmbedContentResponse
      else scale (`div` 2) (EmbedContentResponse <$> arbitrary <*> arbitrary)

instance Arbitrary EmbeddingUsageMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkEmbeddingUsageMetadata
      else scale (`div` 2) (EmbeddingUsageMetadata <$> arbitrary <*> arbitrary)

instance Arbitrary Empty where
  arbitrary = pure Empty

instance Arbitrary ExecutableCodeLanguage where
  arbitrary = elements [ExecutableCodeLanguageLanguageUnspecified, ExecutableCodeLanguagePython]

instance Arbitrary ExecutableCode where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkExecutableCode <$> arbitrary <*> arbitrary
      else scale (`div` 2) (ExecutableCode <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FileSource where
  arbitrary = elements [FileSourceSourceUnspecified, FileSourceUploaded, FileSourceGenerated, FileSourceRegistered]

instance Arbitrary FileState where
  arbitrary = elements [FileStateStateUnspecified, FileStateProcessing, FileStateActive, FileStateFailed]

instance Arbitrary File where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkFile
      else scale (`div` 2) (File <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FileData where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkFileData <$> arbitrary
      else scale (`div` 2) (FileData <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FileSearch where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkFileSearch <$> arbitrary
      else scale (`div` 2) (FileSearch <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FunctionCall where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkFunctionCall <$> arbitrary
      else scale (`div` 2) (FunctionCall <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FunctionCallingConfigMode where
  arbitrary = elements [FunctionCallingConfigModeModeUnspecified, FunctionCallingConfigModeAuto, FunctionCallingConfigModeAny, FunctionCallingConfigModeNone, FunctionCallingConfigModeValidated]

instance Arbitrary FunctionCallingConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkFunctionCallingConfig
      else scale (`div` 2) (FunctionCallingConfig <$> arbitrary <*> arbitrary)

instance Arbitrary FunctionDeclarationBehavior where
  arbitrary = elements [FunctionDeclarationBehaviorUnspecified, FunctionDeclarationBehaviorBlocking, FunctionDeclarationBehaviorNonBlocking]

instance Arbitrary FunctionDeclaration where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkFunctionDeclaration <$> arbitrary <*> arbitrary
      else scale (`div` 2) (FunctionDeclaration <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> liftArbitrary flatValue <*> arbitrary <*> liftArbitrary flatValue)

instance Arbitrary FunctionResponseScheduling where
  arbitrary = elements [FunctionResponseSchedulingSchedulingUnspecified, FunctionResponseSchedulingSilent, FunctionResponseSchedulingWhenIdle, FunctionResponseSchedulingInterrupt]

instance Arbitrary FunctionResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkFunctionResponse <$> arbitrary <*> arbitrary
      else scale (`div` 2) (FunctionResponse <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary FunctionResponseBlob where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkFunctionResponseBlob
      else scale (`div` 2) (FunctionResponseBlob <$> arbitrary <*> arbitrary)

instance Arbitrary FunctionResponsePart where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkFunctionResponsePart
      else scale (`div` 2) (FunctionResponsePart <$> arbitrary)

instance Arbitrary GenerateContentRequestServiceTier where
  arbitrary = elements [GenerateContentRequestServiceTierUnspecified, GenerateContentRequestServiceTierStandard, GenerateContentRequestServiceTierFlex, GenerateContentRequestServiceTierPriority]

instance Arbitrary GenerateContentRequest where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkGenerateContentRequest <$> arbitrary <*> arbitrary
      else scale (`div` 2) (GenerateContentRequest <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GenerateContentResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGenerateContentResponse
      else scale (`div` 2) (GenerateContentResponse <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GenerationConfigMediaResolution where
  arbitrary = elements [GenerationConfigMediaResolutionMediaResolutionUnspecified, GenerationConfigMediaResolutionMediaResolutionLow, GenerationConfigMediaResolutionMediaResolutionMedium, GenerationConfigMediaResolutionMediaResolutionHigh]

instance Arbitrary GenerationConfigResponseModalities where
  arbitrary = elements [GenerationConfigResponseModalitiesModalityUnspecified, GenerationConfigResponseModalitiesText, GenerationConfigResponseModalitiesImage, GenerationConfigResponseModalitiesAudio]

instance Arbitrary GenerationConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGenerationConfig
      else scale (`div` 2) (GenerationConfig <$> liftArbitrary flatValue <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> liftArbitrary flatValue <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GoogleAiGenerativelanguageV1betaGroundingSupport where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGoogleAiGenerativelanguageV1betaGroundingSupport
      else scale (`div` 2) (GoogleAiGenerativelanguageV1betaGroundingSupport <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GoogleAiGenerativelanguageV1betaSegment where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGoogleAiGenerativelanguageV1betaSegment
      else scale (`div` 2) (GoogleAiGenerativelanguageV1betaSegment <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GoogleMaps where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGoogleMaps
      else scale (`div` 2) (GoogleMaps <$> arbitrary)

instance Arbitrary GoogleSearch where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGoogleSearch
      else scale (`div` 2) (GoogleSearch <$> arbitrary <*> arbitrary)

instance Arbitrary GoogleSearchRetrieval where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGoogleSearchRetrieval
      else scale (`div` 2) (GoogleSearchRetrieval <$> arbitrary)

instance Arbitrary GroundingAttribution where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingAttribution
      else scale (`div` 2) (GroundingAttribution <$> arbitrary <*> arbitrary)

instance Arbitrary GroundingChunk where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingChunk
      else scale (`div` 2) (GroundingChunk <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GroundingChunkCustomMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingChunkCustomMetadata
      else scale (`div` 2) (GroundingChunkCustomMetadata <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GroundingChunkStringList where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingChunkStringList
      else scale (`div` 2) (GroundingChunkStringList <$> arbitrary)

instance Arbitrary GroundingMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingMetadata
      else scale (`div` 2) (GroundingMetadata <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary GroundingPassageId where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkGroundingPassageId
      else scale (`div` 2) (GroundingPassageId <$> arbitrary <*> arbitrary)

instance Arbitrary Image where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkImage
      else scale (`div` 2) (Image <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ImageConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkImageConfig
      else scale (`div` 2) (ImageConfig <$> arbitrary <*> arbitrary)

instance Arbitrary ImageResponseFormatAspectRatio where
  arbitrary = elements [ImageResponseFormatAspectRatioAspectRatioUnspecified, ImageResponseFormatAspectRatioAspectRatioOneByOne, ImageResponseFormatAspectRatioAspectRatioTwoByThree, ImageResponseFormatAspectRatioAspectRatioThreeByTwo, ImageResponseFormatAspectRatioAspectRatioThreeByFour, ImageResponseFormatAspectRatioAspectRatioFourByThree, ImageResponseFormatAspectRatioAspectRatioFourByFive, ImageResponseFormatAspectRatioAspectRatioFiveByFour, ImageResponseFormatAspectRatioAspectRatioNineBySixteen, ImageResponseFormatAspectRatioAspectRatioSixteenByNine, ImageResponseFormatAspectRatioAspectRatioTwentyOneByNine, ImageResponseFormatAspectRatioAspectRatioOneByEight, ImageResponseFormatAspectRatioAspectRatioEightByOne, ImageResponseFormatAspectRatioAspectRatioOneByFour, ImageResponseFormatAspectRatioAspectRatioFourByOne]

instance Arbitrary ImageResponseFormatDelivery where
  arbitrary = elements [ImageResponseFormatDeliveryDeliveryUnspecified, ImageResponseFormatDeliveryInline, ImageResponseFormatDeliveryUri]

instance Arbitrary ImageResponseFormatImageSize where
  arbitrary = elements [ImageResponseFormatImageSizeImageSizeUnspecified, ImageResponseFormatImageSizeImageSizeFiveTwelve, ImageResponseFormatImageSizeImageSizeOneK, ImageResponseFormatImageSizeImageSizeTwoK, ImageResponseFormatImageSizeImageSizeFourK]

instance Arbitrary ImageResponseFormatMimeType where
  arbitrary = elements [ImageResponseFormatMimeTypeMimeTypeUnspecified, ImageResponseFormatMimeTypeImageJpeg]

instance Arbitrary ImageResponseFormat where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkImageResponseFormat
      else scale (`div` 2) (ImageResponseFormat <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ImageSearch where
  arbitrary = pure ImageSearch

instance Arbitrary Interval where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkInterval
      else scale (`div` 2) (Interval <$> arbitrary <*> arbitrary)

instance Arbitrary LanguageAuto where
  arbitrary = pure LanguageAuto

instance Arbitrary LanguageHints where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkLanguageHints <$> arbitrary
      else scale (`div` 2) (LanguageHints <$> arbitrary)

instance Arbitrary LatLng where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkLatLng
      else scale (`div` 2) (LatLng <$> arbitrary <*> arbitrary)

instance Arbitrary ListCachedContentsResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkListCachedContentsResponse
      else scale (`div` 2) (ListCachedContentsResponse <$> arbitrary <*> arbitrary)

instance Arbitrary ListFilesResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkListFilesResponse
      else scale (`div` 2) (ListFilesResponse <$> arbitrary <*> arbitrary)

instance Arbitrary ListModelsResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkListModelsResponse
      else scale (`div` 2) (ListModelsResponse <$> arbitrary <*> arbitrary)

instance Arbitrary LogprobsResult where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkLogprobsResult
      else scale (`div` 2) (LogprobsResult <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary LogprobsResultCandidate where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkLogprobsResultCandidate
      else scale (`div` 2) (LogprobsResultCandidate <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary Maps where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkMaps
      else scale (`div` 2) (Maps <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary McpServer where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkMcpServer
      else scale (`div` 2) (McpServer <$> arbitrary <*> arbitrary)

instance Arbitrary ModalityTokenCountModality where
  arbitrary = elements [ModalityTokenCountModalityModalityUnspecified, ModalityTokenCountModalityText, ModalityTokenCountModalityImage, ModalityTokenCountModalityVideo, ModalityTokenCountModalityAudio, ModalityTokenCountModalityDocument]

instance Arbitrary ModalityTokenCount where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkModalityTokenCount
      else scale (`div` 2) (ModalityTokenCount <$> arbitrary <*> arbitrary)

instance Arbitrary Model where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkModel <$> arbitrary <*> arbitrary <*> arbitrary
      else scale (`div` 2) (Model <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ModelStatusModelStage where
  arbitrary = elements [ModelStatusModelStageModelStageUnspecified, ModelStatusModelStageUnstableExperimental, ModelStatusModelStageExperimental, ModelStatusModelStagePreview, ModelStatusModelStageStable, ModelStatusModelStageLegacy, ModelStatusModelStageDeprecated, ModelStatusModelStageRetired]

instance Arbitrary ModelStatus where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkModelStatus
      else scale (`div` 2) (ModelStatus <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary MultiSpeakerVoiceConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkMultiSpeakerVoiceConfig <$> arbitrary
      else scale (`div` 2) (MultiSpeakerVoiceConfig <$> arbitrary)

instance Arbitrary PartMediaProcessing where
  arbitrary = elements [PartMediaProcessingMediaProcessingUnspecified, PartMediaProcessingStatic, PartMediaProcessingAgentic]

instance Arbitrary Part where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkPart
      else scale (`div` 2) (Part <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary PlaceAnswerSources where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkPlaceAnswerSources
      else scale (`div` 2) (PlaceAnswerSources <$> arbitrary)

instance Arbitrary PrebuiltVoiceConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkPrebuiltVoiceConfig
      else scale (`div` 2) (PrebuiltVoiceConfig <$> arbitrary)

instance Arbitrary PromptFeedbackBlockReason where
  arbitrary = elements [PromptFeedbackBlockReasonBlockReasonUnspecified, PromptFeedbackBlockReasonSafety, PromptFeedbackBlockReasonOther, PromptFeedbackBlockReasonBlocklist, PromptFeedbackBlockReasonProhibitedContent, PromptFeedbackBlockReasonImageSafety]

instance Arbitrary PromptFeedback where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkPromptFeedback
      else scale (`div` 2) (PromptFeedback <$> arbitrary <*> arbitrary)

instance Arbitrary ResponseFormatConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkResponseFormatConfig
      else scale (`div` 2) (ResponseFormatConfig <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary RetrievalConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkRetrievalConfig
      else scale (`div` 2) (RetrievalConfig <$> arbitrary <*> arbitrary)

instance Arbitrary RetrievalMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkRetrievalMetadata
      else scale (`div` 2) (RetrievalMetadata <$> arbitrary)

instance Arbitrary RetrievedContext where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkRetrievedContext
      else scale (`div` 2) (RetrievedContext <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ReviewSnippet where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkReviewSnippet
      else scale (`div` 2) (ReviewSnippet <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary SafetyRatingCategory where
  arbitrary = elements [SafetyRatingCategoryHarmCategoryUnspecified, SafetyRatingCategoryHarmCategoryDerogatory, SafetyRatingCategoryHarmCategoryToxicity, SafetyRatingCategoryHarmCategoryViolence, SafetyRatingCategoryHarmCategorySexual, SafetyRatingCategoryHarmCategoryMedical, SafetyRatingCategoryHarmCategoryDangerous, SafetyRatingCategoryHarmCategoryHarassment, SafetyRatingCategoryHarmCategoryHateSpeech, SafetyRatingCategoryHarmCategorySexuallyExplicit, SafetyRatingCategoryHarmCategoryDangerousContent, SafetyRatingCategoryHarmCategoryCivicIntegrity, SafetyRatingCategoryHarmCategoryJailbreak]

instance Arbitrary SafetyRatingProbability where
  arbitrary = elements [SafetyRatingProbabilityHarmProbabilityUnspecified, SafetyRatingProbabilityNegligible, SafetyRatingProbabilityLow, SafetyRatingProbabilityMedium, SafetyRatingProbabilityHigh]

instance Arbitrary SafetyRating where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkSafetyRating <$> arbitrary <*> arbitrary
      else scale (`div` 2) (SafetyRating <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary SafetySettingCategory where
  arbitrary = elements [SafetySettingCategoryHarmCategoryUnspecified, SafetySettingCategoryHarmCategoryDerogatory, SafetySettingCategoryHarmCategoryToxicity, SafetySettingCategoryHarmCategoryViolence, SafetySettingCategoryHarmCategorySexual, SafetySettingCategoryHarmCategoryMedical, SafetySettingCategoryHarmCategoryDangerous, SafetySettingCategoryHarmCategoryHarassment, SafetySettingCategoryHarmCategoryHateSpeech, SafetySettingCategoryHarmCategorySexuallyExplicit, SafetySettingCategoryHarmCategoryDangerousContent, SafetySettingCategoryHarmCategoryCivicIntegrity, SafetySettingCategoryHarmCategoryJailbreak]

instance Arbitrary SafetySettingThreshold where
  arbitrary = elements [SafetySettingThresholdHarmBlockThresholdUnspecified, SafetySettingThresholdBlockLowAndAbove, SafetySettingThresholdBlockMediumAndAbove, SafetySettingThresholdBlockOnlyHigh, SafetySettingThresholdBlockNone, SafetySettingThresholdOff]

instance Arbitrary SafetySetting where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkSafetySetting <$> arbitrary <*> arbitrary
      else scale (`div` 2) (SafetySetting <$> arbitrary <*> arbitrary)

instance Arbitrary SchemaType where
  arbitrary = elements [SchemaTypeTypeUnspecified, SchemaTypeString, SchemaTypeNumber, SchemaTypeInteger, SchemaTypeBoolean, SchemaTypeArray, SchemaTypeObject, SchemaTypeNull]

instance Arbitrary Schema where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkSchema <$> arbitrary
      else scale (`div` 2) (Schema <$> arbitrary <*> liftArbitrary flatValue <*> arbitrary <*> arbitrary <*> liftArbitrary flatValue <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary SearchEntryPoint where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkSearchEntryPoint
      else scale (`div` 2) (SearchEntryPoint <$> arbitrary <*> arbitrary)

instance Arbitrary SearchTypes where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkSearchTypes
      else scale (`div` 2) (SearchTypes <$> arbitrary <*> arbitrary)

instance Arbitrary SemanticRetrieverChunk where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkSemanticRetrieverChunk
      else scale (`div` 2) (SemanticRetrieverChunk <$> arbitrary <*> arbitrary)

instance Arbitrary SpeakerVoiceConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkSpeakerVoiceConfig <$> arbitrary <*> arbitrary
      else scale (`div` 2) (SpeakerVoiceConfig <$> arbitrary <*> arbitrary)

instance Arbitrary SpeechConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkSpeechConfig
      else scale (`div` 2) (SpeechConfig <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary Status where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkStatus
      else scale (`div` 2) (Status <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary StreamableHttpTransport where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkStreamableHttpTransport
      else scale (`div` 2) (StreamableHttpTransport <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary TextResponseFormatMimeType where
  arbitrary = elements [TextResponseFormatMimeTypeMimeTypeUnspecified, TextResponseFormatMimeTypeApplicationJson, TextResponseFormatMimeTypeTextPlain]

instance Arbitrary TextResponseFormat where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkTextResponseFormat
      else scale (`div` 2) (TextResponseFormat <$> arbitrary <*> liftArbitrary flatValue)

instance Arbitrary ThinkingConfigThinkingLevel where
  arbitrary = elements [ThinkingConfigThinkingLevelThinkingLevelUnspecified, ThinkingConfigThinkingLevelMinimal, ThinkingConfigThinkingLevelLow, ThinkingConfigThinkingLevelMedium, ThinkingConfigThinkingLevelHigh]

instance Arbitrary ThinkingConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkThinkingConfig
      else scale (`div` 2) (ThinkingConfig <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary Tool where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkTool
      else scale (`div` 2) (Tool <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ToolCallToolType where
  arbitrary = elements [ToolCallToolTypeToolTypeUnspecified, ToolCallToolTypeGoogleSearchWeb, ToolCallToolTypeGoogleSearchImage, ToolCallToolTypeUrlContext, ToolCallToolTypeGoogleMaps, ToolCallToolTypeFileSearch]

instance Arbitrary ToolCall where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkToolCall <$> arbitrary
      else scale (`div` 2) (ToolCall <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ToolConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkToolConfig
      else scale (`div` 2) (ToolConfig <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary ToolResponseToolType where
  arbitrary = elements [ToolResponseToolTypeToolTypeUnspecified, ToolResponseToolTypeGoogleSearchWeb, ToolResponseToolTypeGoogleSearchImage, ToolResponseToolTypeUrlContext, ToolResponseToolTypeGoogleMaps, ToolResponseToolTypeFileSearch]

instance Arbitrary ToolResponse where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkToolResponse <$> arbitrary
      else scale (`div` 2) (ToolResponse <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary TopCandidates where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkTopCandidates
      else scale (`div` 2) (TopCandidates <$> arbitrary)

instance Arbitrary TranslationConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkTranslationConfig <$> arbitrary
      else scale (`div` 2) (TranslationConfig <$> arbitrary <*> arbitrary)

instance Arbitrary UrlContext where
  arbitrary = pure UrlContext

instance Arbitrary UrlContextMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkUrlContextMetadata
      else scale (`div` 2) (UrlContextMetadata <$> arbitrary)

instance Arbitrary UrlMetadataUrlRetrievalStatus where
  arbitrary = elements [UrlMetadataUrlRetrievalStatusUrlRetrievalStatusUnspecified, UrlMetadataUrlRetrievalStatusUrlRetrievalStatusSuccess, UrlMetadataUrlRetrievalStatusUrlRetrievalStatusError, UrlMetadataUrlRetrievalStatusUrlRetrievalStatusPaywall, UrlMetadataUrlRetrievalStatusUrlRetrievalStatusUnsafe]

instance Arbitrary UrlMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkUrlMetadata
      else scale (`div` 2) (UrlMetadata <$> arbitrary <*> arbitrary)

instance Arbitrary UsageMetadataServiceTier where
  arbitrary = elements [UsageMetadataServiceTierUnspecified, UsageMetadataServiceTierStandard, UsageMetadataServiceTierFlex, UsageMetadataServiceTierPriority]

instance Arbitrary UsageMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkUsageMetadata
      else scale (`div` 2) (UsageMetadata <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary V1mainMediaResolutionLevel where
  arbitrary = elements [V1mainMediaResolutionLevelMediaResolutionUnspecified, V1mainMediaResolutionLevelMediaResolutionLow, V1mainMediaResolutionLevelMediaResolutionMedium, V1mainMediaResolutionLevelMediaResolutionHigh, V1mainMediaResolutionLevelMediaResolutionUltraHigh]

instance Arbitrary V1mainMediaResolution where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkV1mainMediaResolution
      else scale (`div` 2) (V1mainMediaResolution <$> arbitrary)

instance Arbitrary VideoFileMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkVideoFileMetadata
      else scale (`div` 2) (VideoFileMetadata <$> arbitrary)

instance Arbitrary VideoMetadata where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkVideoMetadata
      else scale (`div` 2) (VideoMetadata <$> arbitrary <*> arbitrary <*> arbitrary)

instance Arbitrary VoiceConfig where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkVoiceConfig
      else scale (`div` 2) (VoiceConfig <$> arbitrary)

instance Arbitrary Web where
  arbitrary = sized $ \d ->
    if d <= 1
      then pure mkWeb
      else scale (`div` 2) (Web <$> arbitrary <*> arbitrary)

instance Arbitrary WebSearch where
  arbitrary = pure WebSearch

instance Arbitrary WordInfo where
  arbitrary = sized $ \d ->
    if d <= 1
      then mkWordInfo <$> arbitrary
      else scale (`div` 2) (WordInfo <$> arbitrary <*> arbitrary <*> arbitrary)

roundTripSpecs :: Spec
roundTripSpecs = describe "JSON round-trip" $ do
  prop "AttributionSourceId" (roundTrip @AttributionSourceId)
  prop "AudioResponseFormat" (roundTrip @AudioResponseFormat)
  prop "AudioResponseFormatDelivery" (roundTrip @AudioResponseFormatDelivery)
  prop "AudioResponseFormatMimeType" (roundTrip @AudioResponseFormatMimeType)
  prop "AudioTranscription" (roundTrip @AudioTranscription)
  prop "AudioTranscriptionConfig" (roundTrip @AudioTranscriptionConfig)
  prop "AudioTranscriptionConfigMode" (roundTrip @AudioTranscriptionConfigMode)
  prop "BatchEmbedContentsRequest" (roundTrip @BatchEmbedContentsRequest)
  prop "BatchEmbedContentsResponse" (roundTrip @BatchEmbedContentsResponse)
  prop "Blob" (roundTrip @Blob)
  prop "CachedContent" (roundTrip @CachedContent)
  prop "CachedContentUsageMetadata" (roundTrip @CachedContentUsageMetadata)
  prop "Candidate" (roundTrip @Candidate)
  prop "CandidateFinishReason" (roundTrip @CandidateFinishReason)
  prop "CitationMetadata" (roundTrip @CitationMetadata)
  prop "CitationSource" (roundTrip @CitationSource)
  prop "CodeExecution" (roundTrip @CodeExecution)
  prop "CodeExecutionResult" (roundTrip @CodeExecutionResult)
  prop "CodeExecutionResultOutcome" (roundTrip @CodeExecutionResultOutcome)
  prop "ComputerUse" (roundTrip @ComputerUse)
  prop "ComputerUseDisabledSafetyPolicies" (roundTrip @ComputerUseDisabledSafetyPolicies)
  prop "ComputerUseEnvironment" (roundTrip @ComputerUseEnvironment)
  prop "Content" (roundTrip @Content)
  prop "ContentEmbedding" (roundTrip @ContentEmbedding)
  prop "CountTokensRequest" (roundTrip @CountTokensRequest)
  prop "CountTokensResponse" (roundTrip @CountTokensResponse)
  prop "CreateFileRequest" (roundTrip @CreateFileRequest)
  prop "CreateFileResponse" (roundTrip @CreateFileResponse)
  prop "DynamicRetrievalConfig" (roundTrip @DynamicRetrievalConfig)
  prop "DynamicRetrievalConfigMode" (roundTrip @DynamicRetrievalConfigMode)
  prop "EmbedContentConfig" (roundTrip @EmbedContentConfig)
  prop "EmbedContentConfigTaskType" (roundTrip @EmbedContentConfigTaskType)
  prop "EmbedContentRequest" (roundTrip @EmbedContentRequest)
  prop "EmbedContentRequestTaskType" (roundTrip @EmbedContentRequestTaskType)
  prop "EmbedContentResponse" (roundTrip @EmbedContentResponse)
  prop "EmbeddingUsageMetadata" (roundTrip @EmbeddingUsageMetadata)
  prop "Empty" (roundTrip @Empty)
  prop "ExecutableCode" (roundTrip @ExecutableCode)
  prop "ExecutableCodeLanguage" (roundTrip @ExecutableCodeLanguage)
  prop "File" (roundTrip @File)
  prop "FileSource" (roundTrip @FileSource)
  prop "FileState" (roundTrip @FileState)
  prop "FileData" (roundTrip @FileData)
  prop "FileSearch" (roundTrip @FileSearch)
  prop "FunctionCall" (roundTrip @FunctionCall)
  prop "FunctionCallingConfig" (roundTrip @FunctionCallingConfig)
  prop "FunctionCallingConfigMode" (roundTrip @FunctionCallingConfigMode)
  prop "FunctionDeclaration" (roundTrip @FunctionDeclaration)
  prop "FunctionDeclarationBehavior" (roundTrip @FunctionDeclarationBehavior)
  prop "FunctionResponse" (roundTrip @FunctionResponse)
  prop "FunctionResponseScheduling" (roundTrip @FunctionResponseScheduling)
  prop "FunctionResponseBlob" (roundTrip @FunctionResponseBlob)
  prop "FunctionResponsePart" (roundTrip @FunctionResponsePart)
  prop "GenerateContentRequest" (roundTrip @GenerateContentRequest)
  prop "GenerateContentRequestServiceTier" (roundTrip @GenerateContentRequestServiceTier)
  prop "GenerateContentResponse" (roundTrip @GenerateContentResponse)
  prop "GenerationConfig" (roundTrip @GenerationConfig)
  prop "GenerationConfigMediaResolution" (roundTrip @GenerationConfigMediaResolution)
  prop "GenerationConfigResponseModalities" (roundTrip @GenerationConfigResponseModalities)
  prop "GoogleAiGenerativelanguageV1betaGroundingSupport" (roundTrip @GoogleAiGenerativelanguageV1betaGroundingSupport)
  prop "GoogleAiGenerativelanguageV1betaSegment" (roundTrip @GoogleAiGenerativelanguageV1betaSegment)
  prop "GoogleMaps" (roundTrip @GoogleMaps)
  prop "GoogleSearch" (roundTrip @GoogleSearch)
  prop "GoogleSearchRetrieval" (roundTrip @GoogleSearchRetrieval)
  prop "GroundingAttribution" (roundTrip @GroundingAttribution)
  prop "GroundingChunk" (roundTrip @GroundingChunk)
  prop "GroundingChunkCustomMetadata" (roundTrip @GroundingChunkCustomMetadata)
  prop "GroundingChunkStringList" (roundTrip @GroundingChunkStringList)
  prop "GroundingMetadata" (roundTrip @GroundingMetadata)
  prop "GroundingPassageId" (roundTrip @GroundingPassageId)
  prop "Image" (roundTrip @Image)
  prop "ImageConfig" (roundTrip @ImageConfig)
  prop "ImageResponseFormat" (roundTrip @ImageResponseFormat)
  prop "ImageResponseFormatAspectRatio" (roundTrip @ImageResponseFormatAspectRatio)
  prop "ImageResponseFormatDelivery" (roundTrip @ImageResponseFormatDelivery)
  prop "ImageResponseFormatImageSize" (roundTrip @ImageResponseFormatImageSize)
  prop "ImageResponseFormatMimeType" (roundTrip @ImageResponseFormatMimeType)
  prop "ImageSearch" (roundTrip @ImageSearch)
  prop "Interval" (roundTrip @Interval)
  prop "LanguageAuto" (roundTrip @LanguageAuto)
  prop "LanguageHints" (roundTrip @LanguageHints)
  prop "LatLng" (roundTrip @LatLng)
  prop "ListCachedContentsResponse" (roundTrip @ListCachedContentsResponse)
  prop "ListFilesResponse" (roundTrip @ListFilesResponse)
  prop "ListModelsResponse" (roundTrip @ListModelsResponse)
  prop "LogprobsResult" (roundTrip @LogprobsResult)
  prop "LogprobsResultCandidate" (roundTrip @LogprobsResultCandidate)
  prop "Maps" (roundTrip @Maps)
  prop "McpServer" (roundTrip @McpServer)
  prop "ModalityTokenCount" (roundTrip @ModalityTokenCount)
  prop "ModalityTokenCountModality" (roundTrip @ModalityTokenCountModality)
  prop "Model" (roundTrip @Model)
  prop "ModelStatus" (roundTrip @ModelStatus)
  prop "ModelStatusModelStage" (roundTrip @ModelStatusModelStage)
  prop "MultiSpeakerVoiceConfig" (roundTrip @MultiSpeakerVoiceConfig)
  prop "Part" (roundTrip @Part)
  prop "PartMediaProcessing" (roundTrip @PartMediaProcessing)
  prop "PlaceAnswerSources" (roundTrip @PlaceAnswerSources)
  prop "PrebuiltVoiceConfig" (roundTrip @PrebuiltVoiceConfig)
  prop "PromptFeedback" (roundTrip @PromptFeedback)
  prop "PromptFeedbackBlockReason" (roundTrip @PromptFeedbackBlockReason)
  prop "ResponseFormatConfig" (roundTrip @ResponseFormatConfig)
  prop "RetrievalConfig" (roundTrip @RetrievalConfig)
  prop "RetrievalMetadata" (roundTrip @RetrievalMetadata)
  prop "RetrievedContext" (roundTrip @RetrievedContext)
  prop "ReviewSnippet" (roundTrip @ReviewSnippet)
  prop "SafetyRating" (roundTrip @SafetyRating)
  prop "SafetyRatingCategory" (roundTrip @SafetyRatingCategory)
  prop "SafetyRatingProbability" (roundTrip @SafetyRatingProbability)
  prop "SafetySetting" (roundTrip @SafetySetting)
  prop "SafetySettingCategory" (roundTrip @SafetySettingCategory)
  prop "SafetySettingThreshold" (roundTrip @SafetySettingThreshold)
  prop "Schema" (roundTrip @Schema)
  prop "SchemaType" (roundTrip @SchemaType)
  prop "SearchEntryPoint" (roundTrip @SearchEntryPoint)
  prop "SearchTypes" (roundTrip @SearchTypes)
  prop "SemanticRetrieverChunk" (roundTrip @SemanticRetrieverChunk)
  prop "SpeakerVoiceConfig" (roundTrip @SpeakerVoiceConfig)
  prop "SpeechConfig" (roundTrip @SpeechConfig)
  prop "Status" (roundTrip @Status)
  prop "StreamableHttpTransport" (roundTrip @StreamableHttpTransport)
  prop "TextResponseFormat" (roundTrip @TextResponseFormat)
  prop "TextResponseFormatMimeType" (roundTrip @TextResponseFormatMimeType)
  prop "ThinkingConfig" (roundTrip @ThinkingConfig)
  prop "ThinkingConfigThinkingLevel" (roundTrip @ThinkingConfigThinkingLevel)
  prop "Tool" (roundTrip @Tool)
  prop "ToolCall" (roundTrip @ToolCall)
  prop "ToolCallToolType" (roundTrip @ToolCallToolType)
  prop "ToolConfig" (roundTrip @ToolConfig)
  prop "ToolResponse" (roundTrip @ToolResponse)
  prop "ToolResponseToolType" (roundTrip @ToolResponseToolType)
  prop "TopCandidates" (roundTrip @TopCandidates)
  prop "TranslationConfig" (roundTrip @TranslationConfig)
  prop "UrlContext" (roundTrip @UrlContext)
  prop "UrlContextMetadata" (roundTrip @UrlContextMetadata)
  prop "UrlMetadata" (roundTrip @UrlMetadata)
  prop "UrlMetadataUrlRetrievalStatus" (roundTrip @UrlMetadataUrlRetrievalStatus)
  prop "UsageMetadata" (roundTrip @UsageMetadata)
  prop "UsageMetadataServiceTier" (roundTrip @UsageMetadataServiceTier)
  prop "V1mainMediaResolution" (roundTrip @V1mainMediaResolution)
  prop "V1mainMediaResolutionLevel" (roundTrip @V1mainMediaResolutionLevel)
  prop "VideoFileMetadata" (roundTrip @VideoFileMetadata)
  prop "VideoMetadata" (roundTrip @VideoMetadata)
  prop "VoiceConfig" (roundTrip @VoiceConfig)
  prop "Web" (roundTrip @Web)
  prop "WebSearch" (roundTrip @WebSearch)
  prop "WordInfo" (roundTrip @WordInfo)
