{-# LANGUAGE OverloadedStrings #-}

-- | Renders a 'Plan' as Haskell source. Pure text; no pretty-printer.
module Emit
  ( emitModel
  , emitApi
  , emitInstances
  , header
  , haddock
  , quote
  , numbered
  ) where

import Data.Text (Text)
import qualified Data.Text as T

import Analyse

header :: Text -> Text
header rev =
  "-- GENERATED by genai-codegen from spec/generativelanguage-v1beta.json (revision "
    <> rev <> "). Do not edit."

-- | One-line Haddock text: newlines collapsed, markup characters escaped.
haddock :: Text -> Text
haddock = T.concatMap esc . T.unwords . T.words
  where
    esc c
      | c `elem` ("\\/'\"@<>[]*#~`" :: String) = T.pack ['\\', c]
      | otherwise = T.singleton c

-- | A @-- |@ Haddock block, or no line at all when the description is empty.
docComment :: Text -> [Text]
docComment d
  | T.null (T.strip d) = []
  | otherwise = ["-- | " <> haddock d]

-- | A trailing @-- ^@ Haddock comment at the given indent, or nothing when the
-- description is empty.
docAfter :: Text -> Text -> Text
docAfter indent d
  | T.null (T.strip d) = ""
  | otherwise = indent <> "-- ^ " <> haddock d

-- | A Haskell string literal.
quote :: Text -> Text
quote = T.pack . show . T.unpack

-- | Prefix the first line with @first@ and the rest with @rest@.
numbered :: Text -> Text -> [Text] -> [Text]
numbered first rest xs = zipWith (\i x -> (if i == (0 :: Int) then first else rest) <> x) [0 ..] xs

emitModel :: Plan -> Text
emitModel plan =
  T.unlines $
    [ header (planRevision plan)
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# LANGUAGE RecordWildCards #-}"
    , "{-# OPTIONS_GHC -Wno-unused-imports #-}"
    , ""
    , "-- | Data types of the Gemini API, generated from Google's Discovery document."
    , "--"
    , "-- Optionality follows proto3 JSON: response-only scalars default when absent"
    , "-- (0, \\\"\\\", False, the @UNSPECIFIED@ enum value), lists and maps default to"
    , "-- empty, nested messages are 'Maybe', request-side scalars are 'Maybe' so that"
    , "-- explicit zero values can be sent. Enums carry an @Unknown@ constructor for"
    , "-- values newer than this file."
    , "module GenAI.Client.Model where"
    , ""
    , "import Data.Aeson"
    , "import Data.Int (Int64)"
    , "import Data.Map.Strict (Map)"
    , "import Data.Maybe (catMaybes)"
    , "import Data.Text (Text)"
    , "import Data.Time (UTCTime)"
    , "import GHC.Generics (Generic)"
    , ""
    , "import GenAI.Client.Types (Base64Bytes (..), I64 (..))"
    , ""
    ]
      ++ concatMap emitType (planTypes plan)

emitType :: TypeDef -> [Text]
emitType t = concatMap emitEnum (tEnums t) ++ emitData t

emitEnum :: EnumDef -> [Text]
emitEnum e =
  docComment (enumDoc e)
    ++ ["data " <> n]
    ++ numbered "  = " "  | " [c <> docAfter " " d | (c, _, d) <- enumCtors e]
    ++ [ "  | " <> n <> "Unknown Text -- ^ A value this module does not know about."
       , "  deriving (Show, Eq, Generic)"
       , ""
       , "instance FromJSON " <> n <> " where"
       , "  parseJSON = withText " <> quote n <> " $ \\t -> pure $ case t of"
       ]
    ++ ["    " <> quote v <> " -> " <> c | (c, v, _) <- enumCtors e]
    ++ [ "    other -> " <> n <> "Unknown other"
       , ""
       , "instance ToJSON " <> n <> " where"
       , "  toJSON x = String $ case x of"
       ]
    ++ ["    " <> c <> " -> " <> quote v | (c, v, _) <- enumCtors e]
    ++ ["    " <> n <> "Unknown other -> other", ""]
  where
    n = enumName e

emitData :: TypeDef -> [Text]
emitData t
  | null fs =
      docComment (tDoc t)
        ++ [ "data " <> n <> " = " <> n
           , "  deriving (Show, Eq, Generic)"
           , ""
           , "-- | This message has no fields."
           , "mk" <> n <> " :: " <> n
           , "mk" <> n <> " = " <> n
           , ""
           , "instance FromJSON " <> n <> " where"
           , "  parseJSON = withObject " <> quote n <> " (\\_ -> pure " <> n <> ")"
           , ""
           , "instance ToJSON " <> n <> " where"
           , "  toJSON _ = object []"
           , ""
           ]
  | otherwise =
      docComment (tDoc t)
        ++ ["data " <> n <> " = " <> n]
        ++ numbered "  { " "  , " [fName f <> " :: !(" <> fType f <> ")" <> docAfter "\n    " (fDoc f) | f <- fs]
        ++ [ "  }"
           , "  deriving (Show, Eq, Generic)"
           , ""
           , "-- | Required fields positional (alphabetical); everything else defaulted."
           , "mk" <> n <> " :: " <> T.concat [fType f <> " -> " | f <- positional] <> n
           , "mk" <> n <> T.concat [" " <> argName f | f <- positional] <> " ="
           , "  " <> n
           ]
        ++ numbered "    { " "    , " [fName f <> " = " <> defaultExpr f | f <- fs]
        ++ [ "    }"
           , ""
           , "instance FromJSON " <> n <> " where"
           , "  parseJSON = withObject " <> quote n <> " $ \\o ->"
           , "    " <> n
           ]
        ++ numbered "      <$> " "      <*> " (map decoder fs)
        ++ [ ""
           , "instance ToJSON " <> n <> " where"
           , "  toJSON " <> n <> "{..} = object $ catMaybes"
           ]
        ++ numbered "    [ " "    , " (map encoder fs)
        ++ ["    ]", ""]
  where
    n = tName t
    fs = tFields t
    positional = filter fPositional fs
    argName f = "arg_" <> fName f
    defaultExpr f
      | fPositional f = argName f
      | otherwise = case fPresence f of
          Required -> argName f
          Optional -> "Nothing"
          Defaulted d -> d
          Mono -> "mempty"

-- | Parenthesised: @<$>@ and @<*>@ are both @infixl 4@, so an unparenthesised
-- @fmap unI64 <$> o .:? k@ inside the applicative chain would group wrongly.
decoder :: Field -> Text
decoder f = "(" <> body <> ")"
  where
    body = case (fPresence f, fWire f) of
      (Required, WPlain) -> "o .: " <> k
      (Required, WInt64) -> "unI64 <$> o .: " <> k
      (Optional, WPlain) -> "o .:? " <> k
      (Optional, WInt64) -> "fmap unI64 <$> o .:? " <> k
      (Defaulted d, WPlain) -> "o .:? " <> k <> " .!= " <> d
      (Defaulted d, WInt64) -> "maybe " <> d <> " unI64 <$> o .:? " <> k
      (Mono, WPlain) -> "o .:? " <> k <> " .!= mempty"
      (Mono, WInt64) -> "map unI64 <$> o .:? " <> k <> " .!= mempty"
    k = quote (fJson f)

encoder :: Field -> Text
encoder f = case (fPresence f, fWire f) of
  (Required, WPlain) -> "Just (" <> k <> " .= " <> v <> ")"
  (Required, WInt64) -> "Just (" <> k <> " .= I64 " <> v <> ")"
  (Defaulted _, WPlain) -> "Just (" <> k <> " .= " <> v <> ")"
  (Defaulted _, WInt64) -> "Just (" <> k <> " .= I64 " <> v <> ")"
  (Optional, WPlain) -> "(" <> k <> " .=) <$> " <> v
  (Optional, WInt64) -> "(" <> k <> " .=) . I64 <$> " <> v
  -- A @Required.@ collection is emitted even when empty: an empty required map
  -- (@FunctionResponse.response@ for a void tool result) and an empty required
  -- list are legitimate payloads, and omitting the key would be invalid.
  (Mono, WPlain)
    | fPositional f -> "Just (" <> k <> " .= " <> v <> ")"
    | otherwise -> "if null " <> v <> " then Nothing else Just (" <> k <> " .= " <> v <> ")"
  (Mono, WInt64)
    | fPositional f -> "Just (" <> k <> " .= map I64 " <> v <> ")"
    | otherwise -> "if null " <> v <> " then Nothing else Just (" <> k <> " .= map I64 " <> v <> ")"
  where
    k = quote (fJson f)
    v = fName f

emitApi :: Plan -> Text
emitApi plan =
  T.unlines $
    [ header (planRevision plan)
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# OPTIONS_GHC -Wno-unused-imports #-}"
    , ""
    , "-- | Endpoint constructors. Run them with 'GenAI.Client.Run.runRequest'."
    , "--"
    , "-- 'generateContent', 'streamGenerateContent', 'countTokens', 'embedContent' and"
    , "-- 'batchEmbedContents' are model-scoped: their model argument accepts a bare"
    , "-- name (@gemini-2.5-flash@) or a @models/@-prefixed one (@models/gemini-2.5-flash@)."
    , "-- Every other endpoint takes the full resource name exactly as Google returns"
    , "-- it (e.g. @files/abc-123@); see each function's Haddock for its required format."
    , "module GenAI.Client.API where"
    , ""
    , "import Data.Aeson (toJSON)"
    , "import Data.Maybe (catMaybes)"
    , "import Data.Text (Text)"
    , ""
    , "import GenAI.Client.Model"
    , "import GenAI.Client.Types"
    , ""
    ]
      ++ concatMap emitEndpoint (planEndpoints plan)

emitEndpoint :: Endpoint -> [Text]
emitEndpoint ep =
  queryDecl
    -- The @METHOD path@ line uses '@'/'/' as literal Haddock code-span
    -- delimiters, so it must NOT go through the 'haddock' escaper (that
    -- escaper would mangle the very characters that make it a code span).
    -- No Discovery path contains an '@', so nothing here needs escaping.
    ++ ["-- | @" <> epHttp ep <> " " <> epPath ep <> "@"]
    ++ concatMap ("--" :) (filter (not . null) [descLines, paramLines])
    ++ [ epName ep <> " :: " <> T.concat (map (<> " -> ") argTypes) <> "Request " <> respTy
       , epName ep <> T.concat (map (" " <>) argNames) <> " ="
       , "  Request"
       , "    { reqMethod = " <> quote (epHttp ep)
       , "    , reqResource = " <> resourceExpr
       , "    , reqQuery = " <> queryExpr
       , "    , reqBody = " <> maybe "Nothing" (const "Just (toJSON body)") (epBody ep)
       , "    , reqAlt = " <> maybe "Nothing" (\a -> "Just " <> quote a) (epAlt ep)
       , "    , reqDecode = " <> maybe "\\_ -> Right ()" (const "decodeJsonBody") (epResponse ep)
       , "    }"
       , ""
       ]
  where
    -- The endpoint's Discovery description: free text, so it does go
    -- through the 'haddock' escaper. Suppressed entirely when empty, same
    -- convention as 'docComment'/'docAfter'.
    descLines
      | T.null (T.strip (epDoc ep)) = []
      | otherwise = ["-- " <> haddock (epDoc ep)]
    -- One Haddock bullet per path parameter that carries a description or a
    -- pattern, so a reader of e.g. 'getModel' sees the required resource-name
    -- shape (Discovery's Format:/Example: prose plus its regex) without
    -- leaving the module. The pattern is wrapped in its own literal '@...@'
    -- code span and, like the METHOD/path line above, left unescaped.
    paramLines = concatMap paramLine (epPathParamDocs ep)
    paramLine p
      | T.null (T.strip (ppdDescription p)) && ppdPattern p == Nothing = []
      | otherwise = ["-- * @" <> ppdName p <> "@: " <> haddock (ppdDescription p) <> patternSuffix p]
    -- The '@...@' delimiters stay unescaped (they're ours, not content), but
    -- '/' inside the pattern itself is backslash-escaped: verified against a
    -- real 'haddock' render that an un-escaped slash *pair* (every anchored
    -- regex here has two, e.g. @^models/[^/]+$@) is parsed as emphasis even
    -- inside a code span, italicising a chunk of the regex. Escaping only
    -- '/' (not '[' ']', which trip Haddock's LaTeX-math detection instead)
    -- was confirmed clean by the same manual render.
    patternSuffix p = maybe "" (\pat -> " (pattern: @" <> T.replace "/" "\\/" pat <> "@)") (ppdPattern p)
    qName = upperFirst (epName ep) <> "Query"
    hasQuery = not (null (epQuery ep))
    argTypes = map (const "Text") (epPathParams ep) ++ [qName | hasQuery] ++ maybe [] pure (epBody ep)
    argNames = map ("p_" <>) (epPathParams ep) ++ ["query" | hasQuery] ++ ["body" | Just _ <- [epBody ep]]
    respTy = maybe "()" id (epResponse ep)
    resourceExpr = case epResource ep of
      TplModel verb -> "ModelMethod p_model " <> quote verb
      TplRaw segs -> "RawPath (mconcat [" <> T.intercalate ", " (map segExpr segs) <> "])"
    segExpr (Lit l) = quote l
    segExpr (Param p) = "p_" <> p
    queryExpr
      | hasQuery =
          "catMaybes ["
            <> T.intercalate ", " [qFn (qpType q) <> " " <> quote (qpJson q) <> " (" <> qpField q <> " query)" | q <- epQuery ep]
            <> "]"
      | otherwise = "[]"
    qFn "Int" = "qInt"
    qFn "Bool" = "qBool"
    qFn _ = "qText"
    queryDecl
      | not hasQuery = []
      | otherwise =
          [ "-- | Optional query parameters of '" <> epName ep <> "'."
          , "data " <> qName <> " = " <> qName
          ]
            ++ numbered "  { " "  , " [qpField q <> " :: !(Maybe " <> qpType q <> ")" | q <- epQuery ep]
            ++ [ "  }"
               , "  deriving (Show, Eq)"
               , ""
               , "mk" <> qName <> " :: " <> qName
               , "mk" <> qName <> " = " <> qName <> T.concat (map (const " Nothing") (epQuery ep))
               , ""
               ]

-- | The test module: an 'Arbitrary' instance per generated type and a
-- round-trip property per type.
--
-- Every instance is depth-guarded rather than merely scaled: @Arbitrary
-- (Maybe a)@ is size-independent in QuickCheck, so a self-referential schema
-- (@Schema@ refers to itself through @items@, @properties@ and @anyOf@) would
-- recurse without bound under @scale@ alone. At size <= 1 the generator falls
-- back to @mk<Name>@, which fills every non-positional field with its default
-- and so cannot recurse.
emitInstances :: Plan -> Text
emitInstances plan =
  T.unlines $
    [ header (planRevision plan)
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# OPTIONS_GHC -Wno-orphans -Wno-unused-imports #-}"
    , ""
    , "-- | 'Arbitrary' instances and the JSON round-trip property for every"
    , "-- generated type. Enum generators produce only the known constructors,"
    , "-- never the @Unknown@ fallback, which would decode back to the real"
    , "-- constructor and fail the property for the wrong reason."
    , "module Instances (roundTripSpecs) where"
    , ""
    , "import Data.Aeson (FromJSON, ToJSON, Value (..), decode, encode)"
    , "import qualified Data.ByteString as BS"
    , "import Data.Text (Text)"
    , "import qualified Data.Text as T"
    , "import Data.Time (Day (..), UTCTime (..))"
    , "import Test.Hspec"
    , "import Test.Hspec.QuickCheck (prop)"
    , "import Test.QuickCheck"
    , ""
    , "import GenAI.Client.Model"
    , "import GenAI.Client.Types (Base64Bytes (..))"
    , ""
    , "instance Arbitrary Text where"
    , "  arbitrary = T.pack <$> listOf (elements [\'a\' .. \'z\'])"
    , ""
    , "-- | Whole seconds only: sub-second precision does not survive aeson\'s"
    , "-- RFC3339 round-trip reliably."
    , "instance Arbitrary UTCTime where"
    , "  arbitrary = do"
    , "    d <- choose (0, 40000 :: Integer)"
    , "    s <- choose (0, 86399 :: Integer)"
    , "    pure (UTCTime (ModifiedJulianDay (40587 + d)) (fromInteger s))"
    , ""
    , "-- | A small, flat JSON value, used for every generated \'Value\' field in"
    , "-- place of aeson\'s own instance. Never @Null@: a @Just Null@ in an"
    , "-- optional field encodes as a JSON null, and proto3 JSON reads null as"
    , "-- absent, so it decodes back as \'Nothing\'. Numbers are integral, so the"
    , "-- \'Data.Scientific.Scientific\' hop is exact."
    , "flatValue :: Gen Value"
    , "flatValue ="
    , "  oneof"
    , "    [ String <$> arbitrary"
    , "    , Bool <$> arbitrary"
    , "    , Number . fromInteger <$> arbitrary"
    , "    ]"
    , ""
    , "-- | Any byte string base64-encodes to something the strict decoder accepts."
    , "instance Arbitrary Base64Bytes where"
    , "  arbitrary = Base64Bytes . BS.pack <$> arbitrary"
    , ""
    , "roundTrip :: forall a. (Eq a, ToJSON a, FromJSON a) => a -> Bool"
    , "roundTrip x = decode (encode x) == Just x"
    , ""
    ]
      ++ concatMap emitArb (planTypes plan)
      ++ [ "roundTripSpecs :: Spec"
         , "roundTripSpecs = describe \"JSON round-trip\" $ do"
         ]
      ++ ["  prop " <> quote n <> " (roundTrip @" <> n <> ")" | n <- names]
  where
    names = concat [tName t : map enumName (tEnums t) | t <- planTypes plan]

emitArb :: TypeDef -> [Text]
emitArb t = concatMap enumArb (tEnums t) ++ dataArb
  where
    n = tName t
    fs = tFields t
    positional = filter fPositional fs
    enumArb e =
      [ "instance Arbitrary " <> enumName e <> " where"
      , "  arbitrary = elements [" <> T.intercalate ", " [c | (c, _, _) <- enumCtors e] <> "]"
      , ""
      ]
    dataArb
      | null fs = ["instance Arbitrary " <> n <> " where", "  arbitrary = pure " <> n, ""]
      | otherwise =
          [ "instance Arbitrary " <> n <> " where"
          , "  arbitrary = sized $ \\d ->"
          , "    if d <= 1"
          , "      then " <> base
          , "      else scale (`div` 2) (" <> full <> ")"
          , ""
          ]
    base
      | null positional = "pure mk" <> n
      | otherwise = "mk" <> n <> " <$> " <> T.intercalate " <*> " (map genOf positional)
    full = n <> " <$> " <> T.intercalate " <*> " (map genOf fs)

-- | The generator for one field. Everything goes through 'arbitrary' except
-- 'Value', which uses the Null-free @flatValue@: aeson ships its own
-- @Arbitrary Value@ (so we cannot replace it) and that instance generates
-- @Null@, which no optional field can round-trip.
genOf :: Field -> Text
genOf f = case fType f of
  "Value" -> "flatValue"
  "Maybe Value" -> "liftArbitrary flatValue"
  _ -> "arbitrary"
