{-# LANGUAGE OverloadedStrings #-}

-- | Renders a 'Plan' as Haskell source. Pure text; no pretty-printer.
module Emit
  ( emitModel
  , header
  , haddock
  , quote
  , numbered
  ) where

import Data.Text (Text)
import qualified Data.Text as T

import Analyse

header :: Text -> Text
header rev =
  "-- GENERATED by genai-codegen from spec/generativelanguage-v1beta.json (revision "
    <> rev <> "). Do not edit."

-- | One-line Haddock text: newlines collapsed, markup characters escaped.
haddock :: Text -> Text
haddock = T.concatMap esc . T.unwords . T.words
  where
    esc c
      | c `elem` ("\\/'\"@<>[]*#~`" :: String) = T.pack ['\\', c]
      | otherwise = T.singleton c

-- | A @-- |@ Haddock block, or no line at all when the description is empty.
docComment :: Text -> [Text]
docComment d
  | T.null (T.strip d) = []
  | otherwise = ["-- | " <> haddock d]

-- | A trailing @-- ^@ Haddock comment at the given indent, or nothing when the
-- description is empty.
docAfter :: Text -> Text -> Text
docAfter indent d
  | T.null (T.strip d) = ""
  | otherwise = indent <> "-- ^ " <> haddock d

-- | A Haskell string literal.
quote :: Text -> Text
quote = T.pack . show . T.unpack

-- | Prefix the first line with @first@ and the rest with @rest@.
numbered :: Text -> Text -> [Text] -> [Text]
numbered first rest xs = zipWith (\i x -> (if i == (0 :: Int) then first else rest) <> x) [0 ..] xs

emitModel :: Plan -> Text
emitModel plan =
  T.unlines $
    [ header (planRevision plan)
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# LANGUAGE RecordWildCards #-}"
    , "{-# OPTIONS_GHC -Wno-unused-imports #-}"
    , ""
    , "-- | Data types of the Gemini API, generated from Google's Discovery document."
    , "--"
    , "-- Optionality follows proto3 JSON: response-only scalars default when absent"
    , "-- (0, \\\"\\\", False, the @UNSPECIFIED@ enum value), lists and maps default to"
    , "-- empty, nested messages are 'Maybe', request-side scalars are 'Maybe' so that"
    , "-- explicit zero values can be sent. Enums carry an @Unknown@ constructor for"
    , "-- values newer than this file."
    , "module GenAI.Client.Model where"
    , ""
    , "import Data.Aeson"
    , "import Data.Int (Int64)"
    , "import Data.Map.Strict (Map)"
    , "import Data.Maybe (catMaybes)"
    , "import Data.Text (Text)"
    , "import Data.Time (UTCTime)"
    , "import GHC.Generics (Generic)"
    , ""
    , "import GenAI.Client.Types (Base64Bytes (..), I64 (..))"
    , ""
    ]
      ++ concatMap emitType (planTypes plan)

emitType :: TypeDef -> [Text]
emitType t = concatMap emitEnum (tEnums t) ++ emitData t

emitEnum :: EnumDef -> [Text]
emitEnum e =
  docComment (enumDoc e)
    ++ ["data " <> n]
    ++ numbered "  = " "  | " [c <> docAfter " " d | (c, _, d) <- enumCtors e]
    ++ [ "  | " <> n <> "Unknown Text -- ^ A value this module does not know about."
       , "  deriving (Show, Eq, Generic)"
       , ""
       , "instance FromJSON " <> n <> " where"
       , "  parseJSON = withText " <> quote n <> " $ \\t -> pure $ case t of"
       ]
    ++ ["    " <> quote v <> " -> " <> c | (c, v, _) <- enumCtors e]
    ++ [ "    other -> " <> n <> "Unknown other"
       , ""
       , "instance ToJSON " <> n <> " where"
       , "  toJSON x = String $ case x of"
       ]
    ++ ["    " <> c <> " -> " <> quote v | (c, v, _) <- enumCtors e]
    ++ ["    " <> n <> "Unknown other -> other", ""]
  where
    n = enumName e

emitData :: TypeDef -> [Text]
emitData t
  | null fs =
      docComment (tDoc t)
        ++ [ "data " <> n <> " = " <> n
           , "  deriving (Show, Eq, Generic)"
           , ""
           , "-- | This message has no fields."
           , "mk" <> n <> " :: " <> n
           , "mk" <> n <> " = " <> n
           , ""
           , "instance FromJSON " <> n <> " where"
           , "  parseJSON = withObject " <> quote n <> " (\\_ -> pure " <> n <> ")"
           , ""
           , "instance ToJSON " <> n <> " where"
           , "  toJSON _ = object []"
           , ""
           ]
  | otherwise =
      docComment (tDoc t)
        ++ ["data " <> n <> " = " <> n]
        ++ numbered "  { " "  , " [fName f <> " :: !(" <> fType f <> ")" <> docAfter "\n    " (fDoc f) | f <- fs]
        ++ [ "  }"
           , "  deriving (Show, Eq, Generic)"
           , ""
           , "-- | Required fields positional (alphabetical); everything else defaulted."
           , "mk" <> n <> " :: " <> T.concat [fType f <> " -> " | f <- positional] <> n
           , "mk" <> n <> T.concat [" " <> argName f | f <- positional] <> " ="
           , "  " <> n
           ]
        ++ numbered "    { " "    , " [fName f <> " = " <> defaultExpr f | f <- fs]
        ++ [ "    }"
           , ""
           , "instance FromJSON " <> n <> " where"
           , "  parseJSON = withObject " <> quote n <> " $ \\o ->"
           , "    " <> n
           ]
        ++ numbered "      <$> " "      <*> " (map decoder fs)
        ++ [ ""
           , "instance ToJSON " <> n <> " where"
           , "  toJSON " <> n <> "{..} = object $ catMaybes"
           ]
        ++ numbered "    [ " "    , " (map encoder fs)
        ++ ["    ]", ""]
  where
    n = tName t
    fs = tFields t
    positional = filter fPositional fs
    argName f = "arg_" <> fName f
    defaultExpr f
      | fPositional f = argName f
      | otherwise = case fPresence f of
          Required -> argName f
          Optional -> "Nothing"
          Defaulted d -> d
          Mono -> "mempty"

-- | Parenthesised: @<$>@ and @<*>@ are both @infixl 4@, so an unparenthesised
-- @fmap unI64 <$> o .:? k@ inside the applicative chain would group wrongly.
decoder :: Field -> Text
decoder f = "(" <> body <> ")"
  where
    body = case (fPresence f, fWire f) of
      (Required, WPlain) -> "o .: " <> k
      (Required, WInt64) -> "unI64 <$> o .: " <> k
      (Optional, WPlain) -> "o .:? " <> k
      (Optional, WInt64) -> "fmap unI64 <$> o .:? " <> k
      (Defaulted d, WPlain) -> "o .:? " <> k <> " .!= " <> d
      (Defaulted d, WInt64) -> "maybe " <> d <> " unI64 <$> o .:? " <> k
      (Mono, WPlain) -> "o .:? " <> k <> " .!= mempty"
      (Mono, WInt64) -> "map unI64 <$> o .:? " <> k <> " .!= mempty"
    k = quote (fJson f)

encoder :: Field -> Text
encoder f = case (fPresence f, fWire f) of
  (Required, WPlain) -> "Just (" <> k <> " .= " <> v <> ")"
  (Required, WInt64) -> "Just (" <> k <> " .= I64 " <> v <> ")"
  (Defaulted _, WPlain) -> "Just (" <> k <> " .= " <> v <> ")"
  (Defaulted _, WInt64) -> "Just (" <> k <> " .= I64 " <> v <> ")"
  (Optional, WPlain) -> "(" <> k <> " .=) <$> " <> v
  (Optional, WInt64) -> "(" <> k <> " .=) . I64 <$> " <> v
  -- A @Required.@ collection is emitted even when empty: an empty required map
  -- (@FunctionResponse.response@ for a void tool result) and an empty required
  -- list are legitimate payloads, and omitting the key would be invalid.
  (Mono, WPlain)
    | fPositional f -> "Just (" <> k <> " .= " <> v <> ")"
    | otherwise -> "if null " <> v <> " then Nothing else Just (" <> k <> " .= " <> v <> ")"
  (Mono, WInt64)
    | fPositional f -> "Just (" <> k <> " .= map I64 " <> v <> ")"
    | otherwise -> "if null " <> v <> " then Nothing else Just (" <> k <> " .= map I64 " <> v <> ")"
  where
    k = quote (fJson f)
    v = fName f
