-- GENERATED by genai-codegen from spec/generativelanguage-v1beta.json (revision 20260831). Do not edit.
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | Endpoint constructors. Run them with 'GenAI.Client.Run.runRequest'.
-- Model arguments accept @gemini-2.5-flash@ or @models/gemini-2.5-flash@;
-- other resource names are passed as Google returns them (@files/abc@).
module GenAI.Client.API where

import Data.Aeson (toJSON)
import Data.Maybe (catMaybes)
import Data.Text (Text)

import GenAI.Client.Model
import GenAI.Client.Types

-- | \@POST v1beta\/cachedContents\@
--
-- Creates CachedContent resource.
createCachedContent :: CachedContent -> Request CachedContent
createCachedContent body =
  Request
    { reqMethod = "POST"
    , reqResource = RawPath (mconcat ["cachedContents"])
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@DELETE v1beta\/{+name}\@
--
-- Deletes CachedContent resource.
deleteCachedContent :: Text -> Request ()
deleteCachedContent p_name =
  Request
    { reqMethod = "DELETE"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = []
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = \_ -> Right ()
    }

-- | \@GET v1beta\/{+name}\@
--
-- Reads CachedContent resource.
getCachedContent :: Text -> Request CachedContent
getCachedContent p_name =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = []
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | Optional query parameters of 'listCachedContents'.
data ListCachedContentsQuery = ListCachedContentsQuery
  { listCachedContentsPageSize :: !(Maybe Int)
  , listCachedContentsPageToken :: !(Maybe Text)
  }
  deriving (Show, Eq)

mkListCachedContentsQuery :: ListCachedContentsQuery
mkListCachedContentsQuery = ListCachedContentsQuery Nothing Nothing

-- | \@GET v1beta\/cachedContents\@
--
-- Lists CachedContents.
listCachedContents :: ListCachedContentsQuery -> Request ListCachedContentsResponse
listCachedContents query =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat ["cachedContents"])
    , reqQuery = catMaybes [qInt "pageSize" (listCachedContentsPageSize query), qText "pageToken" (listCachedContentsPageToken query)]
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | Optional query parameters of 'patchCachedContent'.
data PatchCachedContentQuery = PatchCachedContentQuery
  { patchCachedContentUpdateMask :: !(Maybe Text)
  }
  deriving (Show, Eq)

mkPatchCachedContentQuery :: PatchCachedContentQuery
mkPatchCachedContentQuery = PatchCachedContentQuery Nothing

-- | \@PATCH v1beta\/{+name}\@
--
-- Updates CachedContent resource (only expiration is updatable).
patchCachedContent :: Text -> PatchCachedContentQuery -> CachedContent -> Request CachedContent
patchCachedContent p_name query body =
  Request
    { reqMethod = "PATCH"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = catMaybes [qText "updateMask" (patchCachedContentUpdateMask query)]
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@DELETE v1beta\/{+name}\@
--
-- Deletes the \`File\`.
deleteFile :: Text -> Request ()
deleteFile p_name =
  Request
    { reqMethod = "DELETE"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = []
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = \_ -> Right ()
    }

-- | \@GET v1beta\/{+name}\@
--
-- Gets the metadata for the given \`File\`.
getFile :: Text -> Request File
getFile p_name =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = []
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | Optional query parameters of 'listFiles'.
data ListFilesQuery = ListFilesQuery
  { listFilesPageSize :: !(Maybe Int)
  , listFilesPageToken :: !(Maybe Text)
  }
  deriving (Show, Eq)

mkListFilesQuery :: ListFilesQuery
mkListFilesQuery = ListFilesQuery Nothing Nothing

-- | \@GET v1beta\/files\@
--
-- Lists the metadata for \`File\`s owned by the requesting project.
listFiles :: ListFilesQuery -> Request ListFilesResponse
listFiles query =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat ["files"])
    , reqQuery = catMaybes [qInt "pageSize" (listFilesPageSize query), qText "pageToken" (listFilesPageToken query)]
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@POST v1beta\/{+model}:batchEmbedContents\@
--
-- Generates multiple embedding vectors from the input \`Content\` which consists of a batch of strings represented as \`EmbedContentRequest\` objects.
batchEmbedContents :: Text -> BatchEmbedContentsRequest -> Request BatchEmbedContentsResponse
batchEmbedContents p_model body =
  Request
    { reqMethod = "POST"
    , reqResource = ModelMethod p_model ":batchEmbedContents"
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@POST v1beta\/{+model}:countTokens\@
--
-- Runs a model\'s tokenizer on input \`Content\` and returns the token count. Refer to the \[tokens guide\](https:\/\/ai.google.dev\/gemini-api\/docs\/tokens) to learn more about tokens.
countTokens :: Text -> CountTokensRequest -> Request CountTokensResponse
countTokens p_model body =
  Request
    { reqMethod = "POST"
    , reqResource = ModelMethod p_model ":countTokens"
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@POST v1beta\/{+model}:embedContent\@
--
-- Generates a text embedding vector from the input \`Content\` using the specified \[Gemini Embedding model\](https:\/\/ai.google.dev\/gemini-api\/docs\/models\/gemini\#text-embedding).
embedContent :: Text -> EmbedContentRequest -> Request EmbedContentResponse
embedContent p_model body =
  Request
    { reqMethod = "POST"
    , reqResource = ModelMethod p_model ":embedContent"
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@POST v1beta\/{+model}:generateContent\@
--
-- Generates a model response given an input \`GenerateContentRequest\`. Refer to the \[text generation guide\](https:\/\/ai.google.dev\/gemini-api\/docs\/text-generation) for detailed usage information. Input capabilities differ between models, including tuned models. Refer to the \[model guide\](https:\/\/ai.google.dev\/gemini-api\/docs\/models\/gemini) and \[tuning guide\](https:\/\/ai.google.dev\/gemini-api\/docs\/model-tuning) for details.
generateContent :: Text -> GenerateContentRequest -> Request GenerateContentResponse
generateContent p_model body =
  Request
    { reqMethod = "POST"
    , reqResource = ModelMethod p_model ":generateContent"
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@GET v1beta\/{+name}\@
--
-- Gets information about a specific \`Model\` such as its version number, token limits, \[parameters\](https:\/\/ai.google.dev\/gemini-api\/docs\/models\/generative-models\#model-parameters) and other metadata. Refer to the \[Gemini models guide\](https:\/\/ai.google.dev\/gemini-api\/docs\/models\/gemini) for detailed model information.
getModel :: Text -> Request Model
getModel p_name =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat [p_name])
    , reqQuery = []
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | Optional query parameters of 'listModels'.
data ListModelsQuery = ListModelsQuery
  { listModelsPageSize :: !(Maybe Int)
  , listModelsPageToken :: !(Maybe Text)
  }
  deriving (Show, Eq)

mkListModelsQuery :: ListModelsQuery
mkListModelsQuery = ListModelsQuery Nothing Nothing

-- | \@GET v1beta\/models\@
--
-- Lists the \[\`Model\`s\](https:\/\/ai.google.dev\/gemini-api\/docs\/models\/gemini) available through the Gemini API.
listModels :: ListModelsQuery -> Request ListModelsResponse
listModels query =
  Request
    { reqMethod = "GET"
    , reqResource = RawPath (mconcat ["models"])
    , reqQuery = catMaybes [qInt "pageSize" (listModelsPageSize query), qText "pageToken" (listModelsPageToken query)]
    , reqBody = Nothing
    , reqAlt = Nothing
    , reqDecode = decodeJsonBody
    }

-- | \@POST v1beta\/{+model}:streamGenerateContent\@
--
-- Generates a \[streamed response\](https:\/\/ai.google.dev\/gemini-api\/docs\/text-generation?lang=python\#generate-a-text-stream) from the model given an input \`GenerateContentRequest\`.
streamGenerateContent :: Text -> GenerateContentRequest -> Request GenerateContentResponse
streamGenerateContent p_model body =
  Request
    { reqMethod = "POST"
    , reqResource = ModelMethod p_model ":streamGenerateContent"
    , reqQuery = []
    , reqBody = Just (toJSON body)
    , reqAlt = Just "sse"
    , reqDecode = decodeJsonBody
    }

